### ISSUE TITLE
Can't verify hashes

### ISSUE THREAD

**Issue by AhmedJamali** [yaksilab/silver-dollop#1]
Hi, trying to install the requirements following the instructions I get the following error: 

(astroglial_analysis) C:\...\silver-dollop>pip install -r requirements.txt
Ignoring appnope: markers 'python_version >= "3.9" and python_version < "3.13" and platform_system == "Darwin"' don't match your environment

Collecting astroglial-segmentation@ git+https://github.com/yaksilab/Astrolglial-cell-segmentation.git@43481a039ce72fe43b041ef5c2d241e3b1bb748f (from -r requirements.txt (line 35))

ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    astroglial-segmentation@ git+https://github.com/yaksilab/Astrolglial-cell-segmentation.git@43481a039ce72fe43b041ef5c2d241e3b1bb748f from git+https://github.com/yaksilab/Astrolglial-cell-segmentation.git@43481a039ce72fe43b041ef5c2d241e3b1bb748f (from -r requirements.txt (line 35))

**Comment by javidaf** [comment]
This is fixed by d22790c7fb514e7632062dbe746c79f7f335d548
